# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'manage_user.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(345, 186)
        font = QtGui.QFont()
        font.setFamily("PingFang SC")
        font.setPointSize(12)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.line_userPhone = QtWidgets.QLineEdit(self.centralwidget)
        self.line_userPhone.setGeometry(QtCore.QRect(120, 40, 171, 28))
        self.line_userPhone.setText("")
        self.line_userPhone.setObjectName("line_userPhone")
        self.lb_userPhone = QtWidgets.QLabel(self.centralwidget)
        self.lb_userPhone.setGeometry(QtCore.QRect(40, 40, 71, 28))
        self.lb_userPhone.setObjectName("lb_userPhone")
        self.lb_userName = QtWidgets.QLabel(self.centralwidget)
        self.lb_userName.setGeometry(QtCore.QRect(40, 80, 71, 28))
        self.lb_userName.setObjectName("lb_userName")
        self.line_userName = QtWidgets.QLineEdit(self.centralwidget)
        self.line_userName.setGeometry(QtCore.QRect(120, 80, 171, 28))
        self.line_userName.setText("")
        self.line_userName.setObjectName("line_userName")
        self.btn_delete = QtWidgets.QPushButton(self.centralwidget)
        self.btn_delete.setGeometry(QtCore.QRect(220, 130, 91, 31))
        self.btn_delete.setObjectName("btn_delete")
        self.btn_rename = QtWidgets.QPushButton(self.centralwidget)
        self.btn_rename.setGeometry(QtCore.QRect(130, 130, 81, 31))
        self.btn_rename.setObjectName("btn_rename")
        self.btn_create = QtWidgets.QPushButton(self.centralwidget)
        self.btn_create.setGeometry(QtCore.QRect(30, 130, 91, 31))
        self.btn_create.setObjectName("btn_create")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "用户管理"))
        self.lb_userPhone.setText(_translate("MainWindow", "手机号:"))
        self.lb_userName.setText(_translate("MainWindow", "用户名："))
        self.btn_delete.setText(_translate("MainWindow", "删除用户"))
        self.btn_rename.setText(_translate("MainWindow", "重命名"))
        self.btn_create.setText(_translate("MainWindow", "创建用户"))
