# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'manage_grant.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_manage_grant(object):
    def setupUi(self, manage_grant):
        manage_grant.setObjectName("manage_grant")
        manage_grant.resize(334, 184)
        self.lb_username = QtWidgets.QLabel(manage_grant)
        self.lb_username.setGeometry(QtCore.QRect(40, 30, 64, 31))
        font = QtGui.QFont()
        font.setFamily("PingFang SC")
        font.setPointSize(12)
        self.lb_username.setFont(font)
        self.lb_username.setObjectName("lb_username")
        self.line_username = QtWidgets.QLineEdit(manage_grant)
        self.line_username.setGeometry(QtCore.QRect(110, 30, 167, 28))
        font = QtGui.QFont()
        font.setFamily("PingFang SC")
        font.setPointSize(12)
        self.line_username.setFont(font)
        self.line_username.setObjectName("line_username")
        self.widget = QtWidgets.QWidget(manage_grant)
        self.widget.setGeometry(QtCore.QRect(50, 80, 216, 68))
        self.widget.setObjectName("widget")
        self.formLayout = QtWidgets.QFormLayout(self.widget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.btn_grant_select = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("PingFang SC")
        font.setPointSize(12)
        self.btn_grant_select.setFont(font)
        self.btn_grant_select.setObjectName("btn_grant_select")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.btn_grant_select)
        self.btn_revoke_select = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("PingFang SC")
        font.setPointSize(12)
        self.btn_revoke_select.setFont(font)
        self.btn_revoke_select.setObjectName("btn_revoke_select")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.btn_revoke_select)
        self.btn_grant_edit = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("PingFang SC")
        font.setPointSize(12)
        self.btn_grant_edit.setFont(font)
        self.btn_grant_edit.setObjectName("btn_grant_edit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.btn_grant_edit)
        self.btn_revoke_edit = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("PingFang SC")
        font.setPointSize(12)
        self.btn_revoke_edit.setFont(font)
        self.btn_revoke_edit.setObjectName("btn_revoke_edit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.btn_revoke_edit)

        self.retranslateUi(manage_grant)
        QtCore.QMetaObject.connectSlotsByName(manage_grant)

    def retranslateUi(self, manage_grant):
        _translate = QtCore.QCoreApplication.translate
        manage_grant.setWindowTitle(_translate("manage_grant", "权限管理"))
        self.lb_username.setText(_translate("manage_grant", "用户名："))
        self.btn_grant_select.setText(_translate("manage_grant", "授予查询权限"))
        self.btn_revoke_select.setText(_translate("manage_grant", "收回查询权限"))
        self.btn_grant_edit.setText(_translate("manage_grant", "授予修改权限"))
        self.btn_revoke_edit.setText(_translate("manage_grant", "收回修改权限"))
