# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'manage_admin.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_manage_admin_window(object):
    def setupUi(self, manage_admin_window):
        manage_admin_window.setObjectName("manage_admin_window")
        manage_admin_window.resize(318, 187)
        font = QtGui.QFont()
        font.setFamily("PingFang SC")
        font.setPointSize(12)
        manage_admin_window.setFont(font)
        self.widget = QtWidgets.QWidget(manage_admin_window)
        self.widget.setGeometry(QtCore.QRect(40, 130, 239, 32))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_create = QtWidgets.QPushButton(self.widget)
        self.btn_create.setObjectName("btn_create")
        self.horizontalLayout.addWidget(self.btn_create)
        self.btn_edit = QtWidgets.QPushButton(self.widget)
        self.btn_edit.setObjectName("btn_edit")
        self.horizontalLayout.addWidget(self.btn_edit)
        self.btn_delete = QtWidgets.QPushButton(self.widget)
        self.btn_delete.setObjectName("btn_delete")
        self.horizontalLayout.addWidget(self.btn_delete)
        self.lb_password = QtWidgets.QLabel(manage_admin_window)
        self.lb_password.setGeometry(QtCore.QRect(40, 80, 48, 22))
        self.lb_password.setObjectName("lb_password")
        self.lb_username = QtWidgets.QLabel(manage_admin_window)
        self.lb_username.setGeometry(QtCore.QRect(40, 40, 64, 22))
        self.lb_username.setObjectName("lb_username")
        self.line_password = QtWidgets.QLineEdit(manage_admin_window)
        self.line_password.setGeometry(QtCore.QRect(100, 80, 167, 28))
        self.line_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.line_password.setObjectName("line_password")
        self.line_username = QtWidgets.QLineEdit(manage_admin_window)
        self.line_username.setGeometry(QtCore.QRect(100, 40, 167, 28))
        self.line_username.setObjectName("line_username")

        self.retranslateUi(manage_admin_window)
        QtCore.QMetaObject.connectSlotsByName(manage_admin_window)

    def retranslateUi(self, manage_admin_window):
        _translate = QtCore.QCoreApplication.translate
        manage_admin_window.setWindowTitle(_translate("manage_admin_window", "数据库管理员"))
        self.btn_create.setText(_translate("manage_admin_window", "创建"))
        self.btn_edit.setText(_translate("manage_admin_window", "修改"))
        self.btn_delete.setText(_translate("manage_admin_window", "删除"))
        self.lb_password.setText(_translate("manage_admin_window", "密码："))
        self.lb_username.setText(_translate("manage_admin_window", "用户名："))
